### ISSUE TITLE
list-slave-zones-with-master-servers.php unset variable 

### ISSUE THREAD

**Issue by lateagain** [ClouDNS/cloudns-api-bulk-updates#6] opened 2022-08-04 13:41 UTC
list-slave-zones-with-master-servers.php echos $text before setting it. 
So last entry is lost.

**Comment by yminkov** [comment] 2022-08-05 08:12
Hello,

Thanks for letting us know!

The issue is now fixed and the last entry is shown.

**Closed as completed** 2022-10-12 08:00 UTC
